variables:
- name: TF_VAR_ENVIRONMENT
  value: $(Environment)
- name: TF_VAR_AGENT_POOL
  value: $(AgentPool)
- name: TF_VAR_AZURE_REGION
  value: $(Environment)
- name: TF_VAR_AZURE_SUBSCRIPTION
  value: $(Service_Connection)
- name: TF_VAR_AZURERM_DATABASE_NAME
  value: $(CosmosDB_Database_Name)


- name: TF_VAR_COSMOSDB_COLLECTION_MASTERPACKAGES_NAME
  value: $(CosmosDB_Collection_MasterPackages_Name)
- name: TF_VAR_COSMOSDB_COLLECTION_MASTERPIPELINES_NAME
  value: $(CosmosDB_Collection_MasterPipelines_Name)
- name: TF_VAR_COSMOSDB_COLLECTION_REPORTERPACKAGES_NAME
  value: $(CosmosDB_Collection_ReporterPackages_Name)
- name: TF_VAR_COSMOSDB_COLLECTION_ERRORCODES_NAME
  value: $(CosmosDB_Collection_Errorcodes_Name)

- name: TF_VAR_AZURERM_FRONTEND_NAME
  value: $(Web_Frontend_Name)
- name: TF_VAR_AZURERM_BACKEND_NAME
  value: $(Web_Backend_Name)
- name: TF_VAR_RESOURCE_GROUP_NAME
  value: $(Resource_Group_Name)
- name: TF_VAR_AZURERM_STORAGE_ACCOUNT
  value: $(Staging_Storage_Account_Name)
- name: TF_VAR_AZURERM_STORAGE_CONTAINER
  value: $(Staging_Storage_ContainerName)
- name: TF_VAR_AZURERM_APPCONFIG_NAME
  value: $(Application_Config_Name)
- name: TF_VAR_AZURERM_KEY_VAULT
  value: $(Key_Vault_Name)
- name: TF_VAR_AZURERM_APP_SERVICE_PLAN
  value: $(Service_Plan_Name)
- name: TF_VAR_AZURERM_COSMOSDB_ACCOUNT
  value: $(CosmosDB_Account_Name)
- name: TF_VAR_FAILOVER_LOCATION
  value: $(Resource_Region_Failover_Location)
- name: TF_VAR_AZURERM_JWT_SECRET
  value: $(JWTSecret)
- name: TF_VAR_AZURERM_AUTH_TOKEN
  value: $(TokenAuth)
- name: TF_VAR_AZURERM_VIRTUAL_NETWORK_NAME
  value: $(Vnet_Name)
- name: TF_VAR_AZURERM_WEB_FRONTEND_SUBNET_NAME
  value: $(Web_Frontend_Subnet_Name)
- name: TF_VAR_AZURERM_WEB_BACKEND_SUBNET_NAME
  value: $(Web_Backend_Subnet_Name)
- name: TF_VAR_AZURERM_VNET_RESOURCE_GROUP_NAME
  value: $(vnet_Resoure_Group_Name)
- name: TF_VAR_AZURERM_INTEGRATION_SUBNET_NAME
  value: $(integration_Subnet_Name)
- name: TF_VAR_AZURERM_VM_SUBNET_NAME
  value: $(vm_Subnet_Name)
- name: TF_VAR_AZURERM_VM_RESOURCE_GROUP_NAME
  value: $(vm_Resource_Group_Name)
- name: TF_VAR_AZURERM_VM_VIRTUAL_NETWORK_NAME
  value: $(vm_vnet_Name)   

- name: TF_VAR_APPCONFIG_STATUS
  value: $(status)
- name: TF_VAR_APPCONFIG_STAGETRIGGERURL
  value: $(stagetriggerurl)
- name: TF_VAR_APPCONFIG_RELEASETRIGGERURL
  value: $(releasetriggerurl)
- name: TF_VAR_APPCONFIG_FEEDID
  value: $(ArtifactFeedID)
- name: TF_VAR_APPCONFIG_ENVIRONMENTSTAGING
  value: $(Resource_Group_Tags_Staging)
- name: TF_VAR_APPCONFIG_ENVIRONMENTRELEASE
  value: $(Resource_Group_Tags_Release)
- name: TF_VAR_APPCONFIG_GATEWAY
  value: $(gateway)
- name: TF_VAR_APPCONFIG_BEURL
  value: $(beurl)